### ISSUE TITLE
面试官：用CSS实现常见的水平垂直居中方案

### ISSUE THREAD

**Issue by charlie-iu** [charlie-iu/blog#23]
在前端开发中，常见的水平垂直居中实现方案有以下几种：

## 使用Flexbox布局
使用Flexbox布局是实现水平垂直居中的最简单方法之一。首先，将父元素设置为Flex容器，然后使用justify-content和align-items属性将子元素水平垂直居中。

 - css
```css
.parent {
  display: flex;
  justify-content: center;
  align-items: center;
}
```

## 使用绝对定位
使用绝对定位是另一种实现水平垂直居中的方法。首先，将父元素设置为相对定位，然后使用绝对定位将子元素居中。

- css

```css
.parent {
  position: relative;
}

.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

## 使用表格布局
使用表格布局也可以实现水平垂直居中。首先，将父元素设置为display: table，然后将子元素设置为display: table-cell，并使用vertical-align属性将子元素垂直居中。

- css
```css
.parent {
  display: table;
}

.child {
  display: table-cell;
  vertical-align: middle;
  text-align: center;
}
```

这些方法都可以实现水平垂直居中，具体使用哪种方法取决于实际情况。
